# Generated by Django 5.0.1 on 2024-01-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Afcon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classement', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Afcon.groupes')),
            ],
        ),
    ]
